services:
  - type: web
    name: grodealz-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://princedubey01011_db_user:o03WjMGGiszgzh5e@cluster1.vdvzsvt.mongodb.net/grodeaz?retryWrites=true&w=majority&appName=Cluster1
      - key: JWT_SECRET
        value: grodeaz_super_secret_key_2024
